//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoHardwC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ingreso
    {
        public int iddetalle_ingreso { get; set; }
        public int idingreso { get; set; }
        public int idarticulo { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual ingreso ingreso { get; set; }
    }
}
